--[[
A Loop level file generated by Loop-LevelEditor.
You should NOT modify this file unless you know what you are doing.
This file is generated at: 2018.02.22 12:21:56
Level editor version: 0.1
--]]

local M = {}
local moduleName = "pixel"
_G[moduleName] = M;

setmetatable(M, {__index = _ENV})
_ENV = M

viewportWidth = 13.733494
viewportHeight = 8.0

cameraX = 3.02521
cameraY = -1.690276

comps = {}

--A BoxBody
BoxBody_1 = {
	idName = "BoxBody_1",
	tag = "terrain",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 0,
	textureAtlas = "pixel.atlas",
	region = "pixel",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 1.0084033,
	positionY = -1.1140456,
	width = 3.1308522,
	height = 2.5738294,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 342, y = 222, width = 326, height = 268},
		outerBounds = {x = 342, y = 222, width = 326, height = 268},
		marginH = 0,
		marginV = 0,
	},
}
comps[1] = BoxBody_1

--A BoxBody
BoxBody_2 = {
	idName = "BoxBody_2",
	tag = "terrain",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 1,
	textureAtlas = "pixel.atlas",
	region = "pixel",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.17453292,
	positionX = 4.244898,
	positionY = -2.5066025,
	width = 3.1308522,
	height = 2.5738294,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.17453292,
		innerBounds = {x = 679, y = 367, width = 326, height = 268},
		outerBounds = {x = 658, y = 341, width = 368, height = 320},
		marginH = 0,
		marginV = 0,
	},
}
comps[2] = BoxBody_2

--A BoxBody
BoxBody_3 = {
	idName = "BoxBody_3",
	tag = "terrain",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 2,
	textureAtlas = "pixel.atlas",
	region = "pixel",
	originXFactor = 0.69631904,
	originYFactor = 0.36795253,
	angle = 0.17453292,
	positionX = 8.268908,
	positionY = -1.6710684,
	width = 3.1308522,
	height = 3.2364945,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = -0.17453292,
		innerBounds = {x = 1034, y = 201, width = 326, height = 337},
		outerBounds = {x = 1000, y = 187, width = 380, height = 389},
		marginH = 0,
		marginV = 0,
	},
}
comps[3] = BoxBody_3

--A BoxBody
BoxBody_4 = {
	idName = "BoxBody_4",
	tag = "terrain",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 3,
	textureAtlas = "pixel.atlas",
	region = "pixel",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -2.1320527,
	positionY = -2.0168066,
	width = 3.1308522,
	height = 3.5918367,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 15, y = 263, width = 326, height = 374},
		outerBounds = {x = 15, y = 263, width = 326, height = 374},
		marginH = 0,
		marginV = 0,
	},
}
comps[4] = BoxBody_4

--A BoxBody
BoxBody_5 = {
	idName = "BoxBody_5",
	tag = "terrain",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 4,
	textureAtlas = "pixel.atlas",
	region = "pixel",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 0.4417767,
	positionY = -3.6110444,
	width = 3.3709483,
	height = 2.785114,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 271, y = 471, width = 351, height = 290},
		outerBounds = {x = 271, y = 471, width = 351, height = 290},
		marginH = 0,
		marginV = 0,
	},
}
comps[5] = BoxBody_5

--A BoxBody
BoxBody_6 = {
	idName = "BoxBody_6",
	tag = "terrain",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 5,
	textureAtlas = "pixel.atlas",
	region = "pixel",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 6.6266503,
	positionY = -4.043217,
	width = 2.1416566,
	height = 1.7575029,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 979, y = 570, width = 223, height = 183},
		outerBounds = {x = 979, y = 570, width = 223, height = 183},
		marginH = 0,
		marginV = 0,
	},
}
comps[6] = BoxBody_6

raw = {
	windowWidth = 1696,
	windowHeight = 1026,
	canvasPositionX = 0,
	canvasPositionY = 0,
	canvasWidth = 1424,
	canvasHeight = 862,
	metersPerPixel = 0.009603841,
	bitNames = {
	},
}
