--[[
A Loop level file generated by Loop-LevelEditor.
You should NOT modify this file unless you know what you are doing.
This file is generated at: 2018.02.20 01:21:41
Level editor version: 0.1
--]]

local M = {}
local moduleName = "pixel"
_G[moduleName] = M;

setmetatable(M, {__index = _ENV})
_ENV = M

viewportWidth = 15.773851
viewportHeight = 8.0

cameraX = 2.2332156
cameraY = -0.60777384

comps = {}

--A BoxBody
BoxBody_1 = {
	idName = "BoxBody_1",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.6,
	friction = 0.4,
	categoryBits = 1,
	maskBits = 65535,
	groupIndex = 0,
	isSensor = false,
	depth = 0,
	textureAtlas = "pixel_test.atlas",
	region = "tree",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -0.819788,
	positionY = -0.89045936,
	width = 1.639576,
	height = 1.9363958,
	marginH = 0.0,
	marginV = 0.28268552,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 284, y = 235, width = 116, height = 137},
		outerBounds = {x = 284, y = 235, width = 116, height = 137},
		marginH = 0,
		marginV = 20,
	},
}
comps[1] = BoxBody_1

--A BoxBody
BoxBody_2 = {
	idName = "BoxBody_2",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.6,
	friction = 0.4,
	categoryBits = 1,
	maskBits = 65535,
	groupIndex = 0,
	isSensor = false,
	depth = 1,
	textureAtlas = "pixel_test.atlas",
	region = "grass",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -0.45229682,
	positionY = -2.0353358,
	width = 5.6113076,
	height = 0.91872793,
	marginH = 0.113074206,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 170, y = 352, width = 397, height = 65},
		outerBounds = {x = 170, y = 352, width = 397, height = 65},
		marginH = 8,
		marginV = 0,
	},
}
comps[2] = BoxBody_2

raw = {
	windowWidth = 1374,
	windowHeight = 748,
	canvasPositionX = 0,
	canvasPositionY = 0,
	canvasWidth = 800,
	canvasHeight = 480,
	bitNames = {
	},
}
