--[[
A Loop level file generated by Loop-LevelEditor.
You should NOT modify this file unless you know what you are doing.
This file is generated at: 2018.03.04 15:29:04
Level editor version: 0.1
--]]

local M = {}
local moduleName = "pixel1"
_G[moduleName] = M;

setmetatable(M, {__index = _ENV})
_ENV = M

viewportWidth = 15.773851
viewportHeight = 8.0

cameraX = 2.2332156
cameraY = -0.60777384

comps = {}

--A BoxBody
BoxBody_1 = {
	idName = "BoxBody_1",
	tag = "terrain",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.8,
	categoryBits = 1,
	maskBits = 65535,
	groupIndex = 0,
	isSensor = false,
	depth = 0,
	textureAtlas = "color_tiles.atlas",
	region = "brown",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -1.7809187,
	positionY = -3.9717314,
	width = 7.9151945,
	height = 1.4416962,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = -6, y = 470, width = 560, height = 102},
		outerBounds = {x = -6, y = 470, width = 560, height = 102},
		marginH = 0,
		marginV = 0,
	},
}
comps[1] = BoxBody_1

--A ChainBody
ChainBody_3 = {
	idName = "ChainBody_3",
	tag = "default",
	compType = "ChainBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.6,
	friction = 0.4,
	categoryBits = 1,
	maskBits = 65535,
	groupIndex = 0,
	isSensor = false,
	depth = 1,
	textureAtlas = "color_tiles.atlas",
	region = "transparent",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -4.7491164,
	positionY = -1.5123675,
	width = 0.90459365,
	height = 0.90459365,
	points = {
		{x = -0.94699645, y = -1.7809187},
		{x = -0.91872793, y = 4.7915196},
	},
	isLoop = false,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 32, y = 315, width = 64, height = 64},
		outerBounds = {x = 32, y = 315, width = 64, height = 64},
		points = {
			{x = -3, y = 473},
			{x = -1, y = 8},
		},
	},
}
comps[2] = ChainBody_3

--A BoxBody
BoxBody_4 = {
	idName = "BoxBody_4",
	tag = "terrain",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.8,
	categoryBits = 1,
	maskBits = 65535,
	groupIndex = 0,
	isSensor = false,
	depth = 2,
	textureAtlas = "color_tiles.atlas",
	region = "brown",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 7.024735,
	positionY = -3.6749117,
	width = 7.9151945,
	height = 2.204947,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 617, y = 422, width = 560, height = 156},
		outerBounds = {x = 617, y = 422, width = 560, height = 156},
		marginH = 0,
		marginV = 0,
	},
}
comps[3] = BoxBody_4

raw = {
	windowWidth = 1374,
	windowHeight = 748,
	canvasPositionX = 0,
	canvasPositionY = 0,
	canvasWidth = 1183,
	canvasHeight = 578,
	metersPerPixel = 0.014134276,
	bitNames = {
	},
}
