--[[
A Loop level file generated by Loop-LevelEditor.
You should NOT modify this file unless you know what you are doing.
This file is generated at: 2018.02.20 21:41:17
Level editor version: 0.1
--]]

local M = {}
local moduleName = "pixel"
_G[moduleName] = M;

setmetatable(M, {__index = _ENV})
_ENV = M

viewportWidth = 9.533101
viewportHeight = 8.0

cameraX = 3.2334495
cameraY = -3.1777003

comps = {}

--A BoxBody
BoxBody_1 = {
	idName = "BoxBody_1",
	tag = "terrain",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 0,
	textureAtlas = "pixel.atlas",
	region = "pixel",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 2.9268293,
	positionY = -3.2334495,
	width = 9.087108,
	height = 7.470383,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 342, y = 222, width = 326, height = 268},
		outerBounds = {x = 342, y = 222, width = 326, height = 268},
		marginH = 0,
		marginV = 0,
	},
}
comps[1] = BoxBody_1

--A BoxBody
BoxBody_2 = {
	idName = "BoxBody_2",
	tag = "terrain",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 1,
	textureAtlas = "pixel.atlas",
	region = "pixel",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 12.320558,
	positionY = -7.2752614,
	width = 9.087108,
	height = 7.470383,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 679, y = 367, width = 326, height = 268},
		outerBounds = {x = 679, y = 367, width = 326, height = 268},
		marginH = 0,
		marginV = 0,
	},
}
comps[2] = BoxBody_2

--A BoxBody
BoxBody_3 = {
	idName = "BoxBody_3",
	tag = "terrain",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 2,
	textureAtlas = "pixel.atlas",
	region = "pixel",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 21.407665,
	positionY = -7.2752614,
	width = 9.087108,
	height = 7.470383,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 1005, y = 367, width = 326, height = 268},
		outerBounds = {x = 1005, y = 367, width = 326, height = 268},
		marginH = 0,
		marginV = 0,
	},
}
comps[3] = BoxBody_3

raw = {
	windowWidth = 608,
	windowHeight = 480,
	canvasPositionX = -345,
	canvasPositionY = -211,
	canvasWidth = 800,
	canvasHeight = 480,
	screenWidth = 342,
	screenHeight = 287,
	bitNames = {
	},
}
