--[[
A Loop level file generated by Loop-LevelEditor.
You should NOT modify this file unless you know what you are doing.
This file is generated at: 2018.02.18 10:53:57
Level editor version: 0.1
--]]

local M = {}
local moduleName = "test"
_G[moduleName] = M;

setmetatable(M, {__index = _ENV})
_ENV = M

viewportWidth = 13.733494
viewportHeight = 8.0

cameraX = 3.02521
cameraY = -1.690276

comps = {}

--A BoxBody
BoxBody_1 = {
	idName = "BoxBody_1",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 0,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -2.2665064,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 150, y = 303, width = 29, height = 106},
		outerBounds = {x = 150, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[1] = BoxBody_1

--A BoxBody
BoxBody_2 = {
	idName = "BoxBody_2",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 1,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -1.9879951,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 179, y = 303, width = 29, height = 106},
		outerBounds = {x = 179, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[2] = BoxBody_2

--A BoxBody
BoxBody_3 = {
	idName = "BoxBody_3",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 2,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -1.7094837,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 208, y = 303, width = 29, height = 106},
		outerBounds = {x = 208, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[3] = BoxBody_3

--A BoxBody
BoxBody_4 = {
	idName = "BoxBody_4",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 3,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -1.4309723,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 237, y = 303, width = 29, height = 106},
		outerBounds = {x = 237, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[4] = BoxBody_4

--A BoxBody
BoxBody_5 = {
	idName = "BoxBody_5",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 4,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -1.1524609,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 266, y = 303, width = 29, height = 106},
		outerBounds = {x = 266, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[5] = BoxBody_5

--A BoxBody
BoxBody_6 = {
	idName = "BoxBody_6",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 5,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -0.8739495,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 295, y = 303, width = 29, height = 106},
		outerBounds = {x = 295, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[6] = BoxBody_6

--A BoxBody
BoxBody_7 = {
	idName = "BoxBody_7",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 6,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -0.5954382,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 324, y = 303, width = 29, height = 106},
		outerBounds = {x = 324, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[7] = BoxBody_7

--A BoxBody
BoxBody_8 = {
	idName = "BoxBody_8",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 7,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -0.31692675,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 353, y = 303, width = 29, height = 106},
		outerBounds = {x = 353, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[8] = BoxBody_8

--A BoxBody
BoxBody_9 = {
	idName = "BoxBody_9",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 8,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -0.038415365,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 382, y = 303, width = 29, height = 106},
		outerBounds = {x = 382, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[9] = BoxBody_9

--A BoxBody
BoxBody_10 = {
	idName = "BoxBody_10",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 9,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 0.24009603,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 411, y = 303, width = 29, height = 106},
		outerBounds = {x = 411, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[10] = BoxBody_10

--A BoxBody
BoxBody_11 = {
	idName = "BoxBody_11",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 10,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 0.51860744,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 440, y = 303, width = 29, height = 106},
		outerBounds = {x = 440, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[11] = BoxBody_11

--A BoxBody
BoxBody_12 = {
	idName = "BoxBody_12",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 11,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 0.79711884,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 469, y = 303, width = 29, height = 106},
		outerBounds = {x = 469, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[12] = BoxBody_12

--A BoxBody
BoxBody_13 = {
	idName = "BoxBody_13",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 12,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 1.0756302,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 498, y = 303, width = 29, height = 106},
		outerBounds = {x = 498, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[13] = BoxBody_13

--A BoxBody
BoxBody_14 = {
	idName = "BoxBody_14",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 13,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 1.3541416,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 527, y = 303, width = 29, height = 106},
		outerBounds = {x = 527, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[14] = BoxBody_14

--A BoxBody
BoxBody_15 = {
	idName = "BoxBody_15",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 14,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 1.632653,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 556, y = 303, width = 29, height = 106},
		outerBounds = {x = 556, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[15] = BoxBody_15

--A BoxBody
BoxBody_16 = {
	idName = "BoxBody_16",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 15,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 1.9111644,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 585, y = 303, width = 29, height = 106},
		outerBounds = {x = 585, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[16] = BoxBody_16

--A BoxBody
BoxBody_17 = {
	idName = "BoxBody_17",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 16,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 2.1896758,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 614, y = 303, width = 29, height = 106},
		outerBounds = {x = 614, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[17] = BoxBody_17

--A BoxBody
BoxBody_18 = {
	idName = "BoxBody_18",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 17,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 2.468187,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 643, y = 303, width = 29, height = 106},
		outerBounds = {x = 643, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[18] = BoxBody_18

--A BoxBody
BoxBody_19 = {
	idName = "BoxBody_19",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 18,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = 1.4901161E-7,
	positionX = 7.6542616,
	positionY = -0.057623047,
	width = 0.2785114,
	height = 3.630252,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = -1.4901161E-7,
		innerBounds = {x = 1183, y = 57, width = 29, height = 378},
		outerBounds = {x = 1183, y = 57, width = 29, height = 378},
		marginH = 0,
		marginV = 0,
	},
}
comps[19] = BoxBody_19

--A BoxBody
BoxBody_20 = {
	idName = "BoxBody_20",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 19,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -2.545018,
	positionY = -1.1140456,
	width = 0.2785114,
	height = 1.0180072,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 121, y = 303, width = 29, height = 106},
		outerBounds = {x = 121, y = 303, width = 29, height = 106},
		marginH = 0,
		marginV = 0,
	},
}
comps[20] = BoxBody_20

--A BoxBody
BoxBody_21 = {
	idName = "BoxBody_21",
	tag = "default",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 20,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -2.545018,
	positionY = 0.6242497,
	width = 0.2785114,
	height = 2.4489796,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 121, y = 48, width = 29, height = 255},
		outerBounds = {x = 121, y = 48, width = 29, height = 255},
		marginH = 0,
		marginV = 0,
	},
}
comps[21] = BoxBody_21

--A ChainBody
ChainBody_22 = {
	idName = "ChainBody_22",
	tag = "default",
	compType = "ChainBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 21,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 7.298919,
	positionY = -1.1812725,
	width = 0.43217286,
	height = 1.3733493,
	points = {
		{x = -0.2112845, y = 0.6818727},
		{x = 0.22088835, y = 0.6818727},
		{x = 0.22088835, y = -0.6914766},
		{x = -0.2112845, y = -0.6914766},
	},
	isLoop = true,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 1138, y = 292, width = 45, height = 143},
		outerBounds = {x = 1138, y = 292, width = 45, height = 143},
		points = {
			{x = 1138, y = 292},
			{x = 1183, y = 292},
			{x = 1183, y = 435},
			{x = 1138, y = 435},
		},
	},
}
comps[22] = ChainBody_22

--A ChainBody
ChainBody_23 = {
	idName = "ChainBody_23",
	tag = "default",
	compType = "ChainBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 22,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 6.8667464,
	positionY = -1.1812725,
	width = 0.43217286,
	height = 1.3733493,
	points = {
		{x = -0.2112845, y = 0.6818727},
		{x = 0.22088835, y = 0.6818727},
		{x = 0.22088835, y = -0.6914766},
		{x = -0.2112845, y = -0.6914766},
	},
	isLoop = true,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 1093, y = 292, width = 45, height = 143},
		outerBounds = {x = 1093, y = 292, width = 45, height = 143},
		points = {
			{x = 1093, y = 292},
			{x = 1138, y = 292},
			{x = 1138, y = 435},
			{x = 1093, y = 435},
		},
	},
}
comps[23] = ChainBody_23

--A ChainBody
ChainBody_27 = {
	idName = "ChainBody_27",
	tag = "default",
	compType = "ChainBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 4,
	maskBits = 2,
	groupIndex = 0,
	isSensor = false,
	depth = 23,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 5.138055,
	positionY = -1.1812725,
	width = 0.43217286,
	height = 1.3733493,
	points = {
		{x = -0.2112845, y = 0.6818727},
		{x = 0.22088835, y = 0.6818727},
		{x = 0.22088835, y = -0.6914766},
		{x = -0.2112845, y = -0.6914766},
	},
	isLoop = true,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 913, y = 292, width = 45, height = 143},
		outerBounds = {x = 913, y = 292, width = 45, height = 143},
		points = {
			{x = 913, y = 292},
			{x = 958, y = 292},
			{x = 958, y = 435},
			{x = 913, y = 435},
		},
	},
}
comps[24] = ChainBody_27

--A ChainBody
ChainBody_28 = {
	idName = "ChainBody_28",
	tag = "default",
	compType = "ChainBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 24,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 4.705882,
	positionY = -1.1812725,
	width = 0.43217286,
	height = 1.3733493,
	points = {
		{x = -0.2112845, y = 0.6818727},
		{x = 0.22088835, y = 0.6818727},
		{x = 0.22088835, y = -0.6914766},
		{x = -0.2112845, y = -0.6914766},
	},
	isLoop = true,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 868, y = 292, width = 45, height = 143},
		outerBounds = {x = 868, y = 292, width = 45, height = 143},
		points = {
			{x = 868, y = 292},
			{x = 913, y = 292},
			{x = 913, y = 435},
			{x = 868, y = 435},
		},
	},
}
comps[25] = ChainBody_28

--A ChainBody
ChainBody_29 = {
	idName = "ChainBody_29",
	tag = "default",
	compType = "ChainBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 25,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 4.2737093,
	positionY = -1.1812725,
	width = 0.43217286,
	height = 1.3733493,
	points = {
		{x = -0.2112845, y = 0.6818727},
		{x = 0.22088835, y = 0.6818727},
		{x = 0.22088835, y = -0.6914766},
		{x = -0.2112845, y = -0.6914766},
	},
	isLoop = true,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 823, y = 292, width = 45, height = 143},
		outerBounds = {x = 823, y = 292, width = 45, height = 143},
		points = {
			{x = 823, y = 292},
			{x = 868, y = 292},
			{x = 868, y = 435},
			{x = 823, y = 435},
		},
	},
}
comps[26] = ChainBody_29

--A ChainBody
ChainBody_30 = {
	idName = "ChainBody_30",
	tag = "default",
	compType = "ChainBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = true,
	depth = 26,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 3.8415365,
	positionY = -1.1812725,
	width = 0.43217286,
	height = 1.3733493,
	points = {
		{x = -0.2112845, y = 0.6818727},
		{x = 0.22088835, y = 0.6818727},
		{x = 0.22088835, y = -0.6914766},
		{x = -0.2112845, y = -0.6914766},
	},
	isLoop = true,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 778, y = 292, width = 45, height = 143},
		outerBounds = {x = 778, y = 292, width = 45, height = 143},
		points = {
			{x = 778, y = 292},
			{x = 823, y = 292},
			{x = 823, y = 435},
			{x = 778, y = 435},
		},
	},
}
comps[27] = ChainBody_30

--A ChainBody
ChainBody_31 = {
	idName = "ChainBody_31",
	tag = "default",
	compType = "ChainBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 27,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 3.4093637,
	positionY = -1.1812725,
	width = 0.43217286,
	height = 1.3733493,
	points = {
		{x = -0.2112845, y = 0.6818727},
		{x = 0.22088835, y = 0.6818727},
		{x = 0.22088835, y = -0.6914766},
		{x = -0.2112845, y = -0.6914766},
	},
	isLoop = true,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 733, y = 292, width = 45, height = 143},
		outerBounds = {x = 733, y = 292, width = 45, height = 143},
		points = {
			{x = 733, y = 292},
			{x = 778, y = 292},
			{x = 778, y = 435},
			{x = 733, y = 435},
		},
	},
}
comps[28] = ChainBody_31

--A ChainBody
ChainBody_32 = {
	idName = "ChainBody_32",
	tag = "default",
	compType = "ChainBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 28,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 2.9771907,
	positionY = -1.1812725,
	width = 0.43217286,
	height = 1.3733493,
	points = {
		{x = -0.2112845, y = 0.6818727},
		{x = 0.22088835, y = 0.6818727},
		{x = 0.22088835, y = -0.6914766},
		{x = -0.2112845, y = -0.6914766},
	},
	isLoop = true,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 688, y = 292, width = 45, height = 143},
		outerBounds = {x = 688, y = 292, width = 45, height = 143},
		points = {
			{x = 688, y = 292},
			{x = 733, y = 292},
			{x = 733, y = 435},
			{x = 688, y = 435},
		},
	},
}
comps[29] = ChainBody_32

--A CircleBody
CircleBody_33 = {
	idName = "CircleBody_33",
	tag = "default",
	compType = "CircleBody",
	bodyType = "DynamicBody",
	density = 0.5,
	restitution = 0.6,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 29,
	textureAtlas = "logo.atlas",
	region = "lua",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -0.3937575,
	positionY = 1.6038415,
	width = 0.43217286,
	height = 0.43217286,
	maigin = 0.096038416,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 337, y = 51, width = 45, height = 45},
		outerBounds = {x = 337, y = 51, width = 45, height = 45},
		margin = 10,
	},
}
comps[30] = CircleBody_33

--A CircleBody
CircleBody_34 = {
	idName = "CircleBody_34",
	tag = "default",
	compType = "CircleBody",
	bodyType = "DynamicBody",
	density = 0.5,
	restitution = 0.6,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 30,
	textureAtlas = "logo.atlas",
	region = "lua",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 0.19207683,
	positionY = 1.1044418,
	width = 0.43217286,
	height = 0.43217286,
	maigin = 0.096038416,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 398, y = 103, width = 45, height = 45},
		outerBounds = {x = 398, y = 103, width = 45, height = 45},
		margin = 10,
	},
}
comps[31] = CircleBody_34

--A CircleBody
CircleBody_35 = {
	idName = "CircleBody_35",
	tag = "default",
	compType = "CircleBody",
	bodyType = "DynamicBody",
	density = 0.5,
	restitution = 0.6,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = true,
	depth = 31,
	textureAtlas = "logo.atlas",
	region = "lua",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 1.0372149,
	positionY = 0.89315724,
	width = 0.43217286,
	height = 0.43217286,
	maigin = 0.096038416,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 486, y = 125, width = 45, height = 45},
		outerBounds = {x = 486, y = 125, width = 45, height = 45},
		margin = 10,
	},
}
comps[32] = CircleBody_35

--A CircleBody
CircleBody_36 = {
	idName = "CircleBody_36",
	tag = "default",
	compType = "CircleBody",
	bodyType = "DynamicBody",
	density = 0.5,
	restitution = 0.6,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 32,
	textureAtlas = "logo.atlas",
	region = "lua",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 1.3445377,
	positionY = 1.45018,
	width = 0.43217286,
	height = 0.43217286,
	maigin = 0.096038416,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 518, y = 67, width = 45, height = 45},
		outerBounds = {x = 518, y = 67, width = 45, height = 45},
		margin = 10,
	},
}
comps[33] = CircleBody_36

--A CircleBody
CircleBody_37 = {
	idName = "CircleBody_37",
	tag = "default",
	compType = "CircleBody",
	bodyType = "DynamicBody",
	density = 0.5,
	restitution = 0.6,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 33,
	textureAtlas = "logo.atlas",
	region = "lua",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 2.1896758,
	positionY = 0.89315724,
	width = 0.43217286,
	height = 0.43217286,
	maigin = 0.096038416,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 606, y = 125, width = 45, height = 45},
		outerBounds = {x = 606, y = 125, width = 45, height = 45},
		margin = 10,
	},
}
comps[34] = CircleBody_37

--A CircleBody
CircleBody_38 = {
	idName = "CircleBody_38",
	tag = "default",
	compType = "CircleBody",
	bodyType = "DynamicBody",
	density = 0.5,
	restitution = 0.6,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 34,
	textureAtlas = "logo.atlas",
	region = "lua",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 2.7082832,
	positionY = 2.055222,
	width = 0.43217286,
	height = 0.43217286,
	maigin = 0.096038416,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 660, y = 4, width = 45, height = 45},
		outerBounds = {x = 660, y = 4, width = 45, height = 45},
		margin = 10,
	},
}
comps[35] = CircleBody_38

--A CircleBody
CircleBody_39 = {
	idName = "CircleBody_39",
	tag = "default",
	compType = "CircleBody",
	bodyType = "DynamicBody",
	density = 0.5,
	restitution = 0.6,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 35,
	textureAtlas = "logo.atlas",
	region = "lua",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 3.812725,
	positionY = 2.0744298,
	width = 0.43217286,
	height = 0.43217286,
	maigin = 0.096038416,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 775, y = 2, width = 45, height = 45},
		outerBounds = {x = 775, y = 2, width = 45, height = 45},
		margin = 10,
	},
}
comps[36] = CircleBody_39

--A CircleBody
CircleBody_40 = {
	idName = "CircleBody_40",
	tag = "default",
	compType = "CircleBody",
	bodyType = "DynamicBody",
	density = 0.5,
	restitution = 0.6,
	friction = 0.4,
	categoryBits = 1,
	maskBits = -1,
	groupIndex = 0,
	isSensor = false,
	depth = 36,
	textureAtlas = "logo.atlas",
	region = "lua",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 4.9747896,
	positionY = 1.6614646,
	width = 0.43217286,
	height = 0.43217286,
	maigin = 0.096038416,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 896, y = 45, width = 45, height = 45},
		outerBounds = {x = 896, y = 45, width = 45, height = 45},
		margin = 10,
	},
}
comps[37] = CircleBody_40

--A CircleBody
CircleBody_41 = {
	idName = "CircleBody_41",
	tag = "default",
	compType = "CircleBody",
	bodyType = "DynamicBody",
	density = 0.5,
	restitution = 0.6,
	friction = 0.4,
	categoryBits = 2,
	maskBits = 4,
	groupIndex = 0,
	isSensor = false,
	depth = 37,
	textureAtlas = "logo.atlas",
	region = "lua",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 5.608643,
	positionY = 1.0756302,
	width = 0.43217286,
	height = 0.43217286,
	maigin = 0.096038416,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 962, y = 106, width = 45, height = 45},
		outerBounds = {x = 962, y = 106, width = 45, height = 45},
		margin = 10,
	},
}
comps[38] = CircleBody_41

--A ChainBody
ChainBody_42 = {
	idName = "ChainBody_42",
	tag = "default",
	compType = "ChainBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 4,
	maskBits = 2,
	groupIndex = 0,
	isSensor = false,
	depth = 38,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 5.570228,
	positionY = -1.1812725,
	width = 0.43217286,
	height = 1.3733493,
	points = {
		{x = -0.2112845, y = 0.6818727},
		{x = 0.22088835, y = 0.6818727},
		{x = 0.22088835, y = -0.6914766},
		{x = -0.2112845, y = -0.6914766},
	},
	isLoop = true,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 958, y = 292, width = 45, height = 143},
		outerBounds = {x = 958, y = 292, width = 45, height = 143},
		points = {
			{x = 958, y = 292},
			{x = 1003, y = 292},
			{x = 1003, y = 435},
			{x = 958, y = 435},
		},
	},
}
comps[39] = ChainBody_42

--A ChainBody
ChainBody_43 = {
	idName = "ChainBody_43",
	tag = "default",
	compType = "ChainBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 4,
	maskBits = 2,
	groupIndex = 0,
	isSensor = false,
	depth = 39,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 6.002401,
	positionY = -1.1812725,
	width = 0.43217286,
	height = 1.3733493,
	points = {
		{x = -0.2112845, y = 0.6818727},
		{x = 0.22088835, y = 0.6818727},
		{x = 0.22088835, y = -0.6914766},
		{x = -0.2112845, y = -0.6914766},
	},
	isLoop = true,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 1003, y = 292, width = 45, height = 143},
		outerBounds = {x = 1003, y = 292, width = 45, height = 143},
		points = {
			{x = 1003, y = 292},
			{x = 1048, y = 292},
			{x = 1048, y = 435},
			{x = 1003, y = 435},
		},
	},
}
comps[40] = ChainBody_43

--A ChainBody
ChainBody_44 = {
	idName = "ChainBody_44",
	tag = "default",
	compType = "ChainBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 4,
	maskBits = 2,
	groupIndex = 0,
	isSensor = false,
	depth = 40,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 6.4345737,
	positionY = -1.1812725,
	width = 0.43217286,
	height = 1.3733493,
	points = {
		{x = -0.2112845, y = 0.6818727},
		{x = 0.22088835, y = 0.6818727},
		{x = 0.22088835, y = -0.6914766},
		{x = -0.2112845, y = -0.6914766},
	},
	isLoop = true,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 1048, y = 292, width = 45, height = 143},
		outerBounds = {x = 1048, y = 292, width = 45, height = 143},
		points = {
			{x = 1048, y = 292},
			{x = 1093, y = 292},
			{x = 1093, y = 435},
			{x = 1048, y = 435},
		},
	},
}
comps[41] = ChainBody_44

raw = {
	windowWidth = 1696,
	windowHeight = 1026,
	canvasPositionX = 0,
	canvasPositionY = 0,
	canvasWidth = 1138,
	canvasHeight = 541,
	bitNames = {
	},
}
