--[[
A Loop level file generated by Loop-LevelEditor.
You should NOT modify this file unless you know what you are doing.
This file is generated at: 2018.02.13 12:13:22
Level editor version: 0.1
--]]

local M = {}
local moduleName = "test"
_G[moduleName] = M;

setmetatable(M, {__index = _ENV})
_ENV = M

viewportWidth = 13.733494
viewportHeight = 8.0

cameraX = 3.02521
cameraY = -1.690276

comps = {}

--A ChainBody
ChainBody_3 = {
	name = "ChainBody_3",
	compType = "ChainBody",
	bodyType = "StaticBody",
	depth = 0,
	textureAtlas = "logo.atlas",
	region = "lua",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -1.3733493,
	positionY = -3.082833,
	width = 0.3265306,
	height = 0.3265306,
	points = {
		{ x = -1.1428571, y = 0.36494598 },
		{ x = -0.6530612, y = 0.3745498 },
		{ x = 0.25930372, y = 0.6818727 },
		{ x = 0.6338535, y = 0.6338535 },
		{ x = 1.1620648, y = 0.57623047 },
		{ x = 1.5942377, y = 0.13445377 },
		{ x = 1.997599, y = -0.15366146 },
		{ x = 2.727491, y = 0.115246095 },
		{ x = 2.8331332, y = 0.20168066 },
		{ x = 3.3037214, y = 0.28811523 },
	},
	isLoop = false,

	-- Extra lua statements
}
comps[1] = ChainBody_3

--A ChainBody
ChainBody_4 = {
	name = "ChainBody_4",
	compType = "ChainBody",
	bodyType = "StaticBody",
	depth = 1,
	textureAtlas = "logo.atlas",
	region = "lua",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 4.5906363,
	positionY = -4.244898,
	width = 0.3265306,
	height = 0.3265306,
	points = {
		{ x = -2.660264, y = 1.45018 },
		{ x = -1.210084, y = 1.1908764 },
		{ x = -0.92196876, y = 0.6818727 },
		{ x = -0.19207683, y = 0.64345735 },
		{ x = 0.66266507, y = 1.0756302 },
		{ x = 1.632653, y = 1.1716686 },
		{ x = 2.1608644, y = 1.1428571 },
		{ x = 2.7370946, y = 1.7575029 },
		{ x = 3.2172868, y = 2.5162065 },
		{ x = 3.495798, y = 2.9387753 },
	},
	isLoop = false,

	-- Extra lua statements
}
comps[2] = ChainBody_4

