--[[
A Loop level file generated by Loop-LevelEditor.
You should NOT modify this file unless you know what you are doing.
This file is generated at: 2018.02.17 02:05:08
Level editor version: 0.1
--]]

local M = {}
local moduleName = "test"
_G[moduleName] = M;

setmetatable(M, {__index = _ENV})
_ENV = M

viewportWidth = 15.773851
viewportHeight = 8.0

cameraX = 2.2332156
cameraY = -0.60777384

comps = {}

--A BoxBody
BoxBody_1 = {
	idName = "BoxBody_1",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.0,
	friction = 0.4,
	categoryBits = 1,
	maskBits = 65535,
	groupIndex = 0,
	depth = 0,
	textureAtlas = "test.atlas",
	region = "ground",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -1.3286219,
	positionY = -3.434629,
	width = 8.7349825,
	height = 2.3180213,
	marginH = 0.0,
	marginV = 0.028268551,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = -3, y = 401, width = 618, height = 164},
		outerBounds = {x = -3, y = 401, width = 618, height = 164},
		marginH = 0,
		marginV = 2,
	},
}
comps[1] = BoxBody_1

--A BoxBody
BoxBody_2 = {
	idName = "BoxBody_2",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.6,
	friction = 0.4,
	categoryBits = 1,
	maskBits = 65535,
	groupIndex = 0,
	depth = 1,
	textureAtlas = "test.atlas",
	region = "cell",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = -1.8939929,
	positionY = 2.6007068,
	width = 7.7314487,
	height = 1.6819788,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = -7, y = -3, width = 547, height = 119},
		outerBounds = {x = -7, y = -3, width = 547, height = 119},
		marginH = 0,
		marginV = 0,
	},
}
comps[2] = BoxBody_2

--A BoxBody
BoxBody_3 = {
	idName = "BoxBody_3",
	compType = "BoxBody",
	bodyType = "StaticBody",
	density = 0.5,
	restitution = 0.6,
	friction = 0.4,
	categoryBits = 1,
	maskBits = 65535,
	groupIndex = 0,
	depth = 2,
	textureAtlas = "test.atlas",
	region = "continue",
	originXFactor = 0.5,
	originYFactor = 0.5,
	angle = -0.0,
	positionX = 5.6254416,
	positionY = -0.96113074,
	width = 4.876325,
	height = 0.26855123,
	marginH = 0.0,
	marginV = 0.0,

	-- Extra lua statements

	-- Raw data
	raw = {
		angle = 0.0,
		innerBounds = {x = 626, y = 299, width = 345, height = 19},
		outerBounds = {x = 626, y = 299, width = 345, height = 19},
		marginH = 0,
		marginV = 0,
	},
}
comps[3] = BoxBody_3

raw = {
	windowWidth = 1374,
	windowHeight = 748,
	canvasPositionX = 0,
	canvasPositionY = 0,
	canvasWidth = 1032,
	canvasHeight = 571,
	bitNames = {
	},
}
